name: CI Develop Nginx Config
on:
  workflow_call:

jobs:
  lint-nginx-config:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Verify if there were changes in ./docker or *.Dockerfile
      - name: "🔍  Verify Changed Nginx configuration"
        uses: tj-actions/changed-files@v23.1
        id: changed-nginx-config
        with:
          files: |
              backend/nginx/config

      - name: Lint Nginx configuration using Gixy
        if: steps.changed-nginx-config.outputs.any_changed == 'true'
        uses: docker://yandex/gixy:latest
        with:
          args: /github/workspace/backend/nginx/config/default.conf